apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: reasonable-iguana-nodejs 
  janus-idp.io/tekton: reasonable-iguana-nodejs
  backstage.io/kubernetes-id: reasonable-iguana-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: reasonable-iguana-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  