apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: reasonable-iguana-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: reasonable-iguana-nodejs 
  name: reasonable-iguana-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: reasonable-iguana-nodejs 
